config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :products_containers do
      collection do
        post :update_positions
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :products_containers, only: [] do
      get :products
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :products_container_products
  has_many :products_containers, through: :products_container_products
end

app/models/spree/products_container.rb
module Spree
  class ProductsContainer < Spree::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: [:slugged, :finders]

    has_many :products_container_products, dependent: :destroy
    has_many :products, -> { reorder('spree_products_container_products.id') },
             through: :products_container_products


    has_attached_file :image,
                      styles: { large: '600x600>' },
                      default_style: :large,
                      url: '/spree/products_containers/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/products_containers/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }

    validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }

    default_scope { order(:position) }

    def slug_candidates
      [:name]
    end
  end
end

app/models/spree/products_container_product.rb
class Spree::ProductsContainerProduct < ActiveRecord::Base
  belongs_to :products_container
  belongs_to :product
end

app/controllers/spree/admin/products_containers_controller.rb
module Spree
  module Admin
    class ProductsContainersController < ResourceController
      before_action :set_object_name
      before_action :parse_product_ids, only: [:create, :update]

      def index
        @products_containers = Spree::ProductsContainer.page(params[:page] || 1).per(50)
      end

      private

      def set_object_name
        @object_name = resource.object_name
        @objects_name = resource.object_name.pluralize
      end

      def parse_product_ids
        parameter = params[resource.object_name]
        if parameter[:product_ids].present?
          parameter[:product_ids] = parameter[:product_ids].split(',')

          # TODO FIXME
          # will recreate all the associations if something changed
          # quick way to always keep the submitted product sorting
          if @object && parameter[:product_ids] != @object.product_ids.map(&:to_s)
            @object.products_container_products.destroy_all
          end
        end
      end
    end
  end
end

app/controllers/spree/api/products_containers_controller.rb
module Spree
  module Api
    class ProductsContainersController < Spree::Api::BaseController

      def products
        object = Spree::ProductsContainer.find(params[:products_container_id].to_i)
        @products = object.products
                     .includes(*product_includes)
                     .page(params[:page])
                     .per(params[:per_page])
      end

    end
  end
end

app/helpers/spree/admin/navigation_helper_decorator.rb
module Spree
  module Admin
    NavigationHelper.module_eval do

      def link_to_preview(resource, options={})
        begin
          url = options[:url] || url_for(resource)
          options[:data] = { action: "preview" }
          options[:class] = "btn btn-primary btn-sm"
          options[:target] = "_blank"
          link_to_with_icon("eye-open", Spree.t(:preview), url, options)
        # object may not have frontend show route
        rescue
          nil
        end
      end

    end
  end
end

app/views/spree/admin/products_containers/_form.html.erb
<span id="object-id" data-object-id="<%= f.object.id %>"></span>

<div data-hook="admin_products_container_form_fields" class="row">
  <div class="col-md-9">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= error_message_on :products_container, :name %>
    <% end %>
    <%= f.field_container :description, class: ['form-group'] do %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <%= error_message_on :products_container, :description %>
    <% end %>
    <%= f.field_container :start_at, class: ['form-group'] do %>
      <%= f.label :start_at %>
      <%= f.text_field :start_at, value: datepicker_field_value(f.object.start_at), class: 'form-control datepicker' %>
      <%= error_message_on :products_container, :start_at %>
    <% end %>
    <%= f.field_container :end_at, class: ['form-group'] do %>
      <%= f.label :end_at %>
      <%= f.text_field :end_at, value: datepicker_field_value(f.object.end_at), class: 'form-control datepicker' %>
      <%= error_message_on :products_container, :end_at %>
    <% end %>
    <%= f.field_container :active, class: ['form-group'] do %>
      <%= f.label :active %>
      <%= f.check_box :active, class: 'form-control' %>
      <%= error_message_on :products_container, :active %>
    <% end %>
    <%= f.field_container :image, class: ['form-group'] do %>
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
      <%= error_message_on :products_container, :image %>
      <% if f.object.image_file_name %>
        <br><br>
        <%= image_tag f.object.image.url(:large) -%>
      <% end %>
    <% end %>
    <%= f.field_container :products, class: ['form-group'] do %>
      <%= f.label :product_ids, Spree.t(:products) %><br />
      <%= f.hidden_field :product_ids, value: f.object.product_ids.join(','), id: 'products_container_products_select' %>
    <% end %>
  </div>
</div>

app/views/spree/admin/products_containers/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing, scope: @objects_name) %>
<% end %>

<div data-hook="admin_<%= @object_name %>_edit_form_header">
  <%= render 'spree/shared/error_messages', target: @object %>
</div>

<div data-hook="admin_<%= @object_name %>_edit_form">
  <%= form_for [:admin, @object] do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', f: f %>
        <%= render 'spree/admin/shared/edit_resource_links' %>
      </div>
    </div>
  <% end %>
</div>

app/views/spree/admin/products_containers/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing, scope: @objects_name) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new, scope: @objects_name),
                     new_object_url,
                     class: 'btn-success',
                     icon: 'add',
                     id: 'admin_new_products_container_link' %>
<% end if can?(:create, Spree::ProductsContainer) %>

<table class="table sortable" id="listing_<%= @objects_name %>" data-hook data-sortable-link="<%= update_positions_admin_products_containers_url %>">
  <thead>
    <tr data-hook="admin_<%= @objects_name %>_index_headers">
      <th class="no-border"></th>
      <th><%= t(:name, scope: "activerecord.attributes.spree/products_container") %></th>
      <th data-hook="admin_<%= @objects_name %>_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @objects.each do |object| %>
      <tr id="<%= spree_dom_id object %>" data-hook="admin_<%= @objects_name %>_index_rows" class="<%= cycle('odd', 'even')%>">
        <td class="move-handle"><span class="icon icon-move handle"></span></td>
        <td><%= link_to object.name, edit_object_url(object) %></td>
        <td data-hook="admin_<%= @objects_name %>_index_row_actions" class="actions text-right">
          <%= link_to_edit object, no_text: true %>
          <%= link_to_preview object, no_text: true %>
          <%= link_to_delete object, no_text: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @objects %>

app/views/spree/admin/products_containers/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new, scope: @object_name.pluralize) %>
<% end %>

<div data-hook="admin_<%= @object_name %>_new_form_header">
  <%= render 'spree/shared/error_messages', target: @object %>
</div>

<div data-hook="admin_<%= @object_name %>_new_form">
  <%= form_for [:admin, @object] do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'form', f: f %>
        <%= render 'spree/admin/shared/new_resource_links' %>
      </div>
    </div>
  <% end %>
</div>